stages:
  - build
  - deploy

build:
  image: node:14
  stage: build
  script:
    - cd FinalAssignment/shop_app
    - npm install
    - npm run build CI=""
    - cp -r ./build $CI_PROJECT_DIR/build
  only:
    - main
  artifacts:
    paths:
      - build/
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - cd build/
    - rsync -rv * $APP_FOLDER