stages:
  - build
  - deploy

build:
  image: node:14
  stage: build
  script:
    - ls -la
    - npm install
    - npm run build
  only:
    - main
  artifacts:
    paths:
      - build/
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - cd build/
    - ls -l
    - cp -r ./* $APP_FOLDER